version: '3.3'
services:
  decadevs_docker_macaulay:
    container_name: decadevs-docker-macaulay
    image: decadevs-docker-macaulay
    build: ./
    ports:
      - '9000:8080'
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - '3340:3306'
    environment:
      MYSQL_ROOT_PASSWORD: emmanuel
      MYSQL_USER: emmanuel
      MYSQL_DATABASE: testdb
      MYSQL_PASSWORD: root

